---
name: drift-plugin-build
run-name: Build Elasticsearch Drift plugin
on:
  push:
  workflow_dispatch:

## Build and create the project on every push to the project
jobs:
  build:
    strategy:
      matrix:
        es_version:
          - 7.17.0
          - 7.17.1
          - 7.17.2
          - 7.17.3
          - 7.17.4
          - 7.17.5
          - 7.17.6
          - 7.17.7
          - 7.17.8
          - 7.17.9
          - 7.17.10
          - 7.17.11
          - 7.17.12
          - 7.17.13
          - 7.17.14
          - 7.17.15
          - 7.17.16
          - 7.17.17
          - 7.17.18
          - 7.17.19
          - 7.17.20
          - 7.17.21
          - 7.17.22
          - 7.17.23
    runs-on: ubuntu-latest
    container:
      image: quay.io/bluebird/java-builder:0.1.0.jdk-17.b35
    steps:
      - uses: actions/checkout@v4
      - name: Add workspace to git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Build plugin from source
        run: |
          make ES_VERSION=${{ matrix.es_version }}
      - name: Run JUnit and Integration test suite
        run: |
          sudo chown -R cicd:cicd $GITHUB_WORKSPACE
          sudo -u cicd PATH="${PATH}" JAVA_HOME="${JAVA_HOME}" M2_HOME="${M2_HOME}" make ES_VERSION=${{ matrix.es_version }} tests
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Test Report ${{ matrix.es_version }}
      - name: Create zip, rpm and deb packages
        run: |
          make clean
          make ES_VERSION=${{ matrix.es_version }} PACKAGE_VERSION=${{ github.run_number }} packages
      - name: Persist drift-plugin artifacts
        uses: actions/upload-artifact@v4
        with:
          name: es-drift-${{ matrix.es_version }}
          path: |
            drift/target/*.jar
            drift/target/releases/*.zip
            drift/target/releases/*.deb
            drift/target/releases/*.rpm
      - name: Publish Debian packages to Cloudsmith
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          export CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }}
          for deb in $(ls drift/target/releases/*-${{ github.run_number }}_all.deb); do
            cloudsmith push deb bluebird/common/any-distro/any-version ${deb};
          done;
      - name: Publish RPM packages to Cloudsmith
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          export CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }}
          for rpm in $(ls drift/target/releases/*-${{ github.run_number }}.noarch.rpm); do
            cloudsmith push rpm bluebird/common/any-distro/any-version ${rpm};
          done;
